#!/bin/bash
# Auto-generate README.md for project

generate_readme() {
    local project_dir="$1"
    local brief="$project_dir/000-brief.md"
    local spec="$project_dir/004-spec.md"
    local tasks="$project_dir/003-task-queue.json"
    local readme="$project_dir/README.md"

    echo "Generating README.md..."

    # Extract project name from brief
    local name=$(grep -A1 "需求描述\|描述\|Description" "$brief" 2>/dev/null | head -3 | tr -d "\n" | head -c 100)
    [[ -z "$name" ]] && name="My Project"

    cat > "$readme" <<EOF
# $name

> Auto-generated from autodev-harness

## 项目介绍

$(tail -n +3 "$brief" 2>/dev/null | head -20)

## 技术栈

$(if [[ -f "$spec" ]]; then
    grep -A10 "Technical Stack\|技术栈" "$spec" 2>/dev/null | head -10 || echo "- React + TypeScript"
fi)

## 快速开始

\`\`\`bash
# 安装依赖
npm install

# 启动开发服务器
npm run dev

# 构建生产版本
npm run build
\`\`\`

## 项目结构

\`\`\`
$(ls -la "$project_dir" 2>/dev/null | grep "^d" | awk "{print \$NF}" | grep -v "^\.\." | grep -v "^\.$" | head -10)
\`\`\`

## 环境变量

\`\`\`bash
# 复制示例配置
cp .env.example .env

# 配置以下变量:
# ANTHROPIC_API_KEY - Claude API Key
# VERBAL_TOKEN - Vercel Token (可选)
# GITHUB_TOKEN - GitHub Token (可选)
\`\`\`

## 文档

- [000-brief.md](000-brief.md) - 原始需求
- [001-research-report.md](001-research-report.md) - 竞品分析
- [002-plan.md](002-plan.md) - 实施计划
- [003-task-queue.json](003-task-queue.json) - 任务队列
- [004-spec.md](004-spec.md) - 产品规格
- [005-eval-rubric.md](005-eval-rubric.md) - 评审标准

---
*Generated by [AutoDevHarness](https://github.com/your-repo/autodev-harness)*
EOF

    echo "README.md created at: $readme"
}
