#!/bin/bash
# =============================================================================
# UI Library - User interface functions and logging
# =============================================================================

# Log file for the project
LOG_FILE=""
CURRENT_PHASE=""

# === Init logging ===
init_logging() {
    local project_dir="$1"
    LOG_FILE="$project_dir/logs/harness.log"
    mkdir -p "$project_dir/logs"
}

# === Logging with file output ===
log() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] $*"
    echo "$msg"
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
}

log_phase() {
    local phase="$1"
    CURRENT_PHASE="$phase"
    log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log "▶ PHASE START: $phase"
    log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

log_step() {
    log "  ➜ $*"
}

log_done() {
    log "✅ DONE: $*"
}

log_error() {
    log "❌ ERROR: $*"
}

warn() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] ⚠️ $*"
    echo "$msg" >&2
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
}

error() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] ❌ $*"
    echo "$msg" >&2
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
    exit 1
}

success() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] ✅ $*"
    echo "$msg"
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
}

# === Infrastructure Config ===
INFRA_URL=""
INFRA_ANON_KEY=""
INFRA_SERVICE_ROLE_KEY=""

# === Collect Infrastructure Config ===
collect_infra_config() {
    local project_dir="$1"
    local infra_file="$project_dir/.infrastructure.conf"

    # Already configured?
    if [[ -f "$infra_file" ]]; then
        log_step "Found existing infra config: $infra_file"
        return 0
    fi

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔧 INFRASTRUCTURE CONFIGURATION"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Before we proceed with planning, we need infrastructure details."
    echo ""

    # Supabase URL
    echo "1) Supabase Project URL:"
    echo "   (e.g., https://xxxxx.supabase.co)"
    read -p "   → " INFRA_URL

    # Supabase Anon Key (for client-side)
    echo ""
    echo "2) Supabase Anon Key (客户端使用):"
    read -p "   → " INFRA_ANON_KEY

    # Supabase Service Role Key (for DDL operations)
    echo ""
    echo "3) Supabase Service Role Key (建表/执行SQL):"
    read -p "   → " INFRA_SERVICE_ROLE_KEY

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Save to project (DO NOT commit this file - contains secrets)
    cat > "$infra_file" <<INFRA_EOF
# Infrastructure Configuration
# Generated by AutoDevHarness
# ⚠️ DO NOT COMMIT THIS FILE TO VERSION CONTROL

SUPABASE_URL="$INFRA_URL"
SUPABASE_ANON_KEY="$INFRA_ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY="$INFRA_SERVICE_ROLE_KEY"
INFRA_EOF

    # Add to .gitignore if not already there
    if [[ -f "$project_dir/.gitignore" ]] && ! grep -q "\.infrastructure\.conf" "$project_dir/.gitignore"; then
        echo ".infrastructure.conf" >> "$project_dir/.gitignore"
    fi

    log_step "Infrastructure config saved: $infra_file"
    log_step "⚠️ .infrastructure.conf added to .gitignore"
}

# === Load Infrastructure Config ===
load_infra_config() {
    local project_dir="$1"
    local infra_file="$project_dir/.infrastructure.conf"

    if [[ ! -f "$infra_file" ]]; then
        return 1
    fi

    set -a
    source "$infra_file"
    set +a

    export SUPABASE_URL
    export SUPABASE_ANON_KEY
    export SUPABASE_SERVICE_ROLE_KEY
}

# === User Confirmation ===
confirm() {
    local question="$1"
    local response=""

    # Non-interactive mode: auto-approve
    if [[ ! -t 0 ]]; then
        return 0
    fi

    # Interactive mode: read user input
    read -p "$question [y/n]: " response
    [[ "$response" =~ ^[Yy]$ ]]
}

# === Confirm Plan ===
# Returns: 0 = approved, 1 = rejected/cancelled
confirm_plan() {
    local plan_file="$1"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📋 PLAN PREVIEW"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Show first 50 lines of plan
    head -50 "$plan_file"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    if ! confirm "Do you approve this plan?"; then
        echo ""
        echo "Options:"
        echo "  1) Modify the plan file and re-run"
        echo "  2) Cancel"
        read -p "Choose [1/2]: " choice

        case "$choice" in
            1)
                log "Edit $plan_file and run: ./autodev-harness.sh -c $PROJECT_DIR"
                return 1
                ;;
            2)
                log "Cancelled"
                return 1
                ;;
        esac
    fi

    log "Plan approved!"
    return 0
}

# === Spinner ===
spin() {
    local pid=$1
    local delay=0.1
    local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'

    while kill -0 $pid 2>/dev/null; do
        local temp="${spinstr#?}"
        printf " [%c]  " "$spinstr"
        spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done

    printf "    \b\b\b\b"
}

# === Search Lazyweb for design references ===
search_lazyweb_refs() {
    local project_dir="$1"
    local plan_file="$project_dir/002-plan.md"

    # Check if Lazyweb token exists
    local token_file="$HOME/.lazyweb/lazyweb_mcp_token"
    if [[ ! -f "$token_file" ]]; then
        echo "# Lazyweb not configured (no token file)"
        return 1
    fi

    local token
    token=$(cat "$token_file" 2>/dev/null)
    if [[ -z "$token" ]]; then
        echo "# Lazyweb not configured (empty token)"
        return 1
    fi

    # Extract key search terms from plan
    local query="mobile app dashboard UI design"
    if [[ -f "$plan_file" ]]; then
        local plan_content
        plan_content=$(cat "$plan_file" 2>/dev/null | head -200)

        if echo "$plan_content" | grep -qi "pet\|宠物"; then
            query="pet care app mobile UI"
        elif echo "$plan_content" | grep -qi "children\|儿童\|kid"; then
            query="children reward app mobile UI"
        elif echo "$plan_content" | grep -qi "dashboard"; then
            query="mobile dashboard UI design"
        elif echo "$plan_content" | grep -qi "gamification"; then
            query="gamification mobile app UI rewards"
        fi
    fi

    echo "# Lazyweb Design References"
    echo "# Query: $query"
    echo ""

    # Try Claude Code MCP call first
    local result
    result=$(claude mcp call lazyweb_search "{\"query\":\"$query\",\"limit\":6}" 2>/dev/null) || true

    if [[ -z "$result" ]] || echo "$result" | grep -qi "error\|unknown command"; then
        # Fallback: direct HTTP request
        result=$(curl -s "https://www.lazyweb.com/mcp" \
            -H "Authorization: Bearer $token" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json, text/event-stream" \
            -d "{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"params\":{\"name\":\"lazyweb_search\",\"arguments\":{\"query\":\"$query\",\"limit\":6}},\"id\":1}" 2>/dev/null) || true
    fi

    # Parse and format results
    if [[ -n "$result" ]] && ! echo "$result" | grep -qi "error"; then
        local tmpfile=$(mktemp)
        # Write to file preserving raw content (avoid echo which corrupts JSON)
        printf '%s' "$result" > "$tmpfile"
        python3 -c "
import sys, json, re
with open(sys.argv[1], 'rb') as f:
    raw = f.read().decode('utf-8', errors='replace')
match = re.search(r'\{[\s\S]*\}', raw)
if match:
    data = json.loads(match.group())
    results = data.get('result', {}).get('content', [{}])
    if results:
        inner_text = results[0].get('text', '{}')
        inner = json.loads(inner_text)
        for ref in inner.get('results', []):
            sim = ref.get('similarity', 0)
            name = ref.get('companyName', 'Unknown')
            platform = ref.get('platform', '')
            cat = ref.get('category', '')
            desc = ref.get('visionDescription', '')[:200]
            print(f'## {name} (similarity: {sim:.2f})')
            print(f'Platform: {platform} | Category: {cat}')
            print(f'Description: {desc}')
            print()
else:
    print('# Failed to parse Lazyweb response')
" "$tmpfile" 2>/dev/null || echo "$result" | head -50
        rm -f "$tmpfile"
    else
        echo "# No results from Lazyweb"
    fi

    return 0
}
