#!/bin/bash
# =============================================================================
# UI Library - User interface functions and logging
# =============================================================================

# Log file for the project
LOG_FILE=""
CURRENT_PHASE=""

# === Init logging ===
init_logging() {
    local project_dir="$1"
    LOG_FILE="$project_dir/logs/harness.log"
    mkdir -p "$project_dir/logs"
}

# === Logging with file output ===
log() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] $*"
    echo "$msg"
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
}

log_phase() {
    local phase="$1"
    CURRENT_PHASE="$phase"
    log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log "▶ PHASE START: $phase"
    log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

log_step() {
    log "  ➜ $*"
}

log_done() {
    log "✅ DONE: $*"
}

log_error() {
    log "❌ ERROR: $*"
}

warn() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] ⚠️ $*"
    echo "$msg" >&2
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
}

error() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] ❌ $*"
    echo "$msg" >&2
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
    exit 1
}

success() {
    local msg="[$(date +%Y-%m-%d\ %H:%M:%S)] [${CURRENT_PHASE:-init}] ✅ $*"
    echo "$msg"
    if [[ -n "$LOG_FILE" ]]; then
        echo "$msg" >> "$LOG_FILE"
    fi
}

# === Infrastructure Config ===
INFRA_URL=""
INFRA_ANON_KEY=""
INFRA_SERVICE_ROLE_KEY=""

# === Collect Infrastructure Config ===
collect_infra_config() {
    local project_dir="$1"
    local infra_file="$project_dir/.infrastructure.conf"

    # Already configured?
    if [[ -f "$infra_file" ]]; then
        log_step "Found existing infra config: $infra_file"
        return 0
    fi

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔧 INFRASTRUCTURE CONFIGURATION"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Before we proceed with planning, we need infrastructure details."
    echo ""

    # Supabase URL
    echo "1) Supabase Project URL:"
    echo "   (e.g., https://xxxxx.supabase.co)"
    read -p "   → " INFRA_URL

    # Supabase Anon Key (for client-side)
    echo ""
    echo "2) Supabase Anon Key (客户端使用):"
    read -p "   → " INFRA_ANON_KEY

    # Supabase Service Role Key (for DDL operations)
    echo ""
    echo "3) Supabase Service Role Key (建表/执行SQL):"
    read -p "   → " INFRA_SERVICE_ROLE_KEY

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Save to project (DO NOT commit this file - contains secrets)
    cat > "$infra_file" <<INFRA_EOF
# Infrastructure Configuration
# Generated by AutoDevHarness
# ⚠️ DO NOT COMMIT THIS FILE TO VERSION CONTROL

SUPABASE_URL="$INFRA_URL"
SUPABASE_ANON_KEY="$INFRA_ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY="$INFRA_SERVICE_ROLE_KEY"
INFRA_EOF

    # Add to .gitignore if not already there
    if [[ -f "$project_dir/.gitignore" ]] && ! grep -q "\.infrastructure\.conf" "$project_dir/.gitignore"; then
        echo ".infrastructure.conf" >> "$project_dir/.gitignore"
    fi

    log_step "Infrastructure config saved: $infra_file"
    log_step "⚠️ .infrastructure.conf added to .gitignore"
}

# === Load Infrastructure Config ===
load_infra_config() {
    local project_dir="$1"
    local infra_file="$project_dir/.infrastructure.conf"

    if [[ ! -f "$infra_file" ]]; then
        return 1
    fi

    set -a
    source "$infra_file"
    set +a

    export SUPABASE_URL
    export SUPABASE_ANON_KEY
    export SUPABASE_SERVICE_ROLE_KEY
}

# === User Confirmation ===
confirm() {
    local question="$1"
    local response=""

    # Non-interactive mode: auto-approve
    if [[ ! -t 0 ]]; then
        return 0
    fi

    # Interactive mode: read user input
    read -p "$question [y/n]: " response
    [[ "$response" =~ ^[Yy]$ ]]
}

# === Confirm Plan ===
# Returns: 0 = approved, 1 = rejected/cancelled
confirm_plan() {
    local plan_file="$1"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📋 PLAN PREVIEW"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Show first 50 lines of plan
    head -50 "$plan_file"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    if ! confirm "Do you approve this plan?"; then
        echo ""
        echo "Options:"
        echo "  1) Modify the plan file and re-run"
        echo "  2) Cancel"
        read -p "Choose [1/2]: " choice

        case "$choice" in
            1)
                log "Edit $plan_file and run: ./autodev-harness.sh -c $PROJECT_DIR"
                return 1
                ;;
            2)
                log "Cancelled"
                return 1
                ;;
        esac
    fi

    log "Plan approved!"
    return 0
}

# === Spinner ===
spin() {
    local pid=$1
    local delay=0.1
    local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'

    while kill -0 $pid 2>/dev/null; do
        local temp="${spinstr#?}"
        printf " [%c]  " "$spinstr"
        spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done

    printf "    \b\b\b\b"
}

# === Search Lazyweb for design references ===
search_lazyweb_refs() {
    local project_dir="$1"
    local plan_file="$project_dir/002-plan.md"

    # Check if Lazyweb token exists
    local token_file="$HOME/.lazyweb/lazyweb_mcp_token"
    if [[ ! -f "$token_file" ]]; then
        echo "# Lazyweb not configured (no token file)"
        return 1
    fi

    local token
    token=$(cat "$token_file" 2>/dev/null)
    if [[ -z "$token" ]]; then
        echo "# Lazyweb not configured (empty token)"
        return 1
    fi

    # Extract key search terms from plan
    local query="mobile app dashboard UI design"
    if [[ -f "$plan_file" ]]; then
        local plan_content
        plan_content=$(cat "$plan_file" 2>/dev/null | head -200)

        if echo "$plan_content" | grep -qi "pet\|宠物"; then
            query="pet care app mobile UI"
        elif echo "$plan_content" | grep -qi "children\|儿童\|kid"; then
            query="children reward app mobile UI"
        elif echo "$plan_content" | grep -qi "dashboard"; then
            query="mobile dashboard UI design"
        elif echo "$plan_content" | grep -qi "gamification"; then
            query="gamification mobile app UI rewards"
        fi
    fi

    echo "# Lazyweb Design References"
    echo "# Query: $query"
    echo ""

    # Try Claude Code MCP call first
    local result
    result=$(claude mcp call lazyweb_search "{\"query\":\"$query\",\"limit\":6}" 2>/dev/null) || true

    if [[ -z "$result" ]] || echo "$result" | grep -qi "error\|unknown command"; then
        # Fallback: direct HTTP request
        result=$(curl -s "https://www.lazyweb.com/mcp" \
            -H "Authorization: Bearer $token" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json, text/event-stream" \
            -d "{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"params\":{\"name\":\"lazyweb_search\",\"arguments\":{\"query\":\"$query\",\"limit\":6}},\"id\":1}" 2>/dev/null) || true
    fi

    # Parse and format results
    if [[ -n "$result" ]] && ! echo "$result" | grep -qi "error"; then
        local tmpfile=$(mktemp)
        # Write to file preserving raw content (avoid echo which corrupts JSON)
        printf '%s' "$result" > "$tmpfile"
        python3 -c "
import sys, json, re
with open(sys.argv[1], 'rb') as f:
    raw = f.read().decode('utf-8', errors='replace')
match = re.search(r'\{[\s\S]*\}', raw)
if match:
    data = json.loads(match.group())
    results = data.get('result', {}).get('content', [{}])
    if results:
        inner_text = results[0].get('text', '{}')
        inner = json.loads(inner_text)
        for ref in inner.get('results', []):
            sim = ref.get('similarity', 0)
            name = ref.get('companyName', 'Unknown')
            platform = ref.get('platform', '')
            cat = ref.get('category', '')
            desc = ref.get('visionDescription', '')[:200]
            print(f'## {name} (similarity: {sim:.2f})')
            print(f'Platform: {platform} | Category: {cat}')
            print(f'Description: {desc}')
            print()
else:
    print('# Failed to parse Lazyweb response')
" "$tmpfile" 2>/dev/null || echo "$result" | head -50
        rm -f "$tmpfile"
    else
        echo "# No results from Lazyweb"
    fi

    return 0
}

# === Search UI/UX Pro Max for Design System ===
search_uiuxpromax_refs() {
    local project_dir="$1"
    local plan_file="$project_dir/002-plan.md"

    # Find the ui-ux-pro-max search script
    local search_script=""
    for dir in \
        "$HOME/.claude/plugins/cache/ui-ux-pro-max-skill/ui-ux-pro-max/2.5.0/src/ui-ux-pro-max/scripts/search.py" \
        "$HOME/.claude/plugins/cache/ui-ux-pro-max-skill/ui-ux-pro-max/2.5.0/cli/assets/scripts/search.py"; do
        if [[ -f "$dir" ]]; then
            search_script="$dir"
            break
        fi
    done

    if [[ -z "$search_script" ]]; then
        echo "# UI/UX Pro Max not available (script not found)"
        return 1
    fi

    # Extract keywords from plan
    local query="mobile app dashboard children gamification"
    if [[ -f "$plan_file" ]]; then
        local plan_content=$(cat "$plan_file" 2>/dev/null | head -100)
        if echo "$plan_content" | grep -qi "pet\|宠物"; then
            query="pet care app children gamification reward"
        elif echo "$plan_content" | grep -qi "children\|儿童\|kid"; then
            query="children reward app gamification mobile"
        fi
    fi

    # Get data dir for the script
    local data_dir=$(dirname "$search_script")/../data
    export PYTHONPATH=$(dirname "$search_script")/..:$PYTHONPATH

    echo "# UI/UX Pro Max Design System"
    echo "# Query: $query"
    echo ""

    # Run the search script with design-system flag
    local result
    result=$(cd "$(dirname "$search_script")" && python3 search.py "$query" --design-system -f markdown 2>/dev/null) || true

    if [[ -n "$result" ]]; then
        echo "$result"
    else
        echo "# No results from UI/UX Pro Max"
    fi

    return 0
}

# === Search Multiple Design References ===
search_design_refs() {
    local project_dir="$1"
    local plan_file="$project_dir/002-plan.md"
    local ref_output="$project_dir/.claude/design-refs.md"

    echo "# Design References (Multiple Sources)" > "$ref_output"
    echo "" >> "$ref_output"

    # 1. Lazyweb References
    local lazyweb_result
    lazyweb_result=$(search_lazyweb_refs "$project_dir" 2>/dev/null) || true
    if [[ -n "$lazyweb_result" && ! "$lazyweb_result" =~ "not configured" ]]; then
        echo "--- Lazyweb (Real App Screenshots) ---" >> "$ref_output"
        echo "$lazyweb_result" >> "$ref_output"
        echo "" >> "$ref_output"
    fi

    # 2. Web Search for High-Quality Design Examples
    local search_query="best UI design examples children's app gamification 2024"
    if [[ -f "$plan_file" ]]; then
        local plan_content=$(cat "$plan_file" 2>/dev/null | head -200)
        if echo "$plan_content" | grep -qi "pet\|宠物"; then
            search_query="best pet care app UI design gamification children"
        fi
    fi

    echo "--- Web Design Inspiration ---" >> "$ref_output"
    echo "# Search query: $search_query" >> "$ref_output"
    echo "" >> "$ref_output"

    # Use Exa web search if available
    local web_results=""
    web_results=$(claude mcp call exa_search "{\"query\":\"$search_query\",\"numResults\":5}" 2>/dev/null) || true

    if [[ -n "$web_results" && ! "$web_results" =~ "error\|unknown command" ]]; then
        echo "$web_results" | python3 -c "
import sys, json, re
raw = sys.stdin.read()
match = re.search(r'\[.*\]', raw, re.DOTALL)
if match:
    try:
        results = json.loads(match.group())
        for r in results[:5]:
            title = r.get('title', '')
            url = r.get('url', '')
            snippet = r.get('snippet', '')[:150]
            print(f'## {title}')
            print(f'URL: {url}')
            print(f'{snippet}')
            print()
    except: pass
" 2>/dev/null >> "$ref_output" || true
    fi

    # 3. Design Principles from ECC Frontend Patterns
    echo "--- ECC Frontend Patterns (UI Best Practices) ---" >> "$ref_output"
    cat >> "$ref_output" << 'PATTERNS'

## 设计原则

### 圆润Q萌风格 (Rounded & Cute)
- 圆角半径: 16-24px (卡片), 12px (按钮), 50% (头像)
- 柔和阴影: box-shadow with blur 20-40px, opacity 0.1-0.15
- 大触摸目标: 最小 48x48px

### 色彩系统
- Primary: 暖橙色 #E85D04 或 成长绿 #059669
- 背景: 奶油白 #FFFBF7, 纯白 #FFFFFF
- 强调色: 金黄 #F59E0B, 成功绿 #10B981

### 字体
- 标题: Nunito (圆润可爱), 28-36px
- 正文: Inter, 16-18px
- 行高: 1.5-1.7

### 动效
- 宠物idle: translateY 浮动 3s ease-in-out infinite
- 按钮反馈: scale 0.95, 150ms ease-out
- 页面切换: fade + slide-up, 300ms ease-out

### 组件模式
- 卡片: 白色背景 + 圆角20px + 柔和阴影
- 底部导航: 固定底部, 白色背景 + 顶部细线
- 进度条: 圆角, 渐变色 (绿→橙→红)

### 儿童友好设计
- 大按钮 (72px+), 高对比度
- 简单图标 + 文字标签
- 正向激励 (星星奖励, 成就徽章)
- 无复杂手势, tap 为主

## 配色参考

| 用途 | 颜色 | Hex |
|------|------|-----|
| Primary | 活力橙 | #E85D04 |
| Secondary | 成长绿 | #059669 |
| Accent | 金黄 | #F59E0B |
| Background | 奶油白 | #FFFBF7 |
| Surface | 纯白 | #FFFFFF |
| Success | 成功绿 | #10B981 |
| Warning | 警告橙 | #F59E0B |
| Error | 错误红 | #EF4444 |

## 布局模式

```
┌─────────────────────────────────────┐
│         Header (固定顶部)            │
│   Logo | 导航标签 | 用户头像          │
├─────────────────────────────────────┤
│                                     │
│         Main Content Area           │
│      (宠物展示 / 任务列表 / 排行榜)    │
│                                     │
├─────────────────────────────────────┤
│       Mobile Bottom Nav (底部)       │
│     首页 | 宠物 | 任务 | 排行榜      │
└─────────────────────────────────────┘
```

响应式断点:
- Mobile: < 640px (单列, 底部导航)
- Tablet: 640px - 1024px (双列)
- Desktop: > 1024px (三列)
PATTERNS

    # 4. UI/UX Pro Max Design System
    local uiuxpro_result
    uiuxpro_result=$(search_uiuxpromax_refs "$project_dir" 2>/dev/null) || true
    if [[ -n "$uiuxpro_result" && ! "$uiuxpro_result" =~ "not available" ]]; then
        echo "" >> "$ref_output"
        echo "--- UI.DEV Pro Max ---" >> "$ref_output"
        echo "$uiuxpro_result" >> "$ref_output"
    fi

    echo "" >> "$ref_output"
    echo "# Generated at $(date +%Y-%m-%d\ %H:%M:%S)" >> "$ref_output"

    # Also output to stdout for logging
    cat "$ref_output"
}

# Alias for backward compatibility
search_lazyweb_refs_multi() {
    search_design_refs "$1"
}
